### ISSUE TITLE
Including aaa without adding anything else to new ACT project will cause an NPE

### ISSUE THREAD

**Issue by CINJ** [actframework/act-aaa-plugin#8]

**Comment by greenlaw110** [comment]
@CINJ can you paste the error stack here?

**Comment by greenlaw110** [comment]
Fixed. Now it will print out a warning and disable aaa plugin if app failed to provide bridge classes

![image](https://user-images.githubusercontent.com/216930/28359778-bb1088b8-6cb6-11e7-86e2-26481f729609.png)
